# Copyright 2026 OpenSourceOM
# SPDX-License-Identifier: Apache-2.0
version: 2

project_name: om

builds:
  - id: om
    main: ./cmd/om
    binary: om
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}
    artifacts: checksum

release:
  draft: false
  prerelease: auto
