{{/*
Copyright 2026 OpenSourceOM
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if eq (include "opensourceom.scan.inline" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensourceom.scan.inlineSecretName" . }}
  labels:
    {{- include "opensourceom.labels" . | nindent 4 }}
    app.kubernetes.io/component: scan
type: Opaque
stringData:
  {{- if and (eq (include "opensourceom.scan.aws.envFrom" .) (include "opensourceom.scan.inlineSecretName" .)) }}
  AWS_ACCESS_KEY_ID: {{ .Values.scan.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.scan.aws.secretAccessKey | quote }}
  {{- end }}
  {{- if and (eq (include "opensourceom.scan.azure.envFrom" .) (include "opensourceom.scan.inlineSecretName" .)) }}
  AZURE_TENANT_ID: {{ .Values.scan.azure.tenantId | quote }}
  AZURE_CLIENT_ID: {{ .Values.scan.azure.clientId | quote }}
  AZURE_CLIENT_SECRET: {{ .Values.scan.azure.clientSecret | quote }}
  {{- end }}
  {{- if eq (include "opensourceom.scan.gcp.secretName" .) (include "opensourceom.scan.inlineSecretName" .) }}
  credentials.json: {{ .Values.scan.gcp.credentialsJson | quote }}
  {{- end }}
{{- end }}
