{{/*
Copyright 2026 OpenSourceOM
SPDX-License-Identifier: Apache-2.0
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensourceom.fullname" . }}
  labels:
    {{- include "opensourceom.labels" . | nindent 4 }}
type: Opaque
stringData:
  OM_API_SECRET: {{ required "api.secret is required" .Values.api.secret | quote }}
  POSTGRES_PASSWORD: {{ required "postgres.password is required" .Values.postgres.password | quote }}
